### ISSUE TITLE
is this program can run without cuda？ and when i run the command "python3 run.py....",an error accured,,,,could you help me to have a look ?

### ISSUE THREAD

**Issue by MacHong01** [mkabelitz/3dgnn#1]
Traceback (most recent call last):
  File "run.py", line 303, in <module>
    main(args.filename)
  File "run.py", line 37, in main
    str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')).replace(' ', '/') + '/'
KeyError: 'name'

**Comment by DrugD** [comment]
I meet this problem too,could you give us a suggestion?
---------------error-------------------
 File "run.py", line 305, in <module>
    main(args.filename)
  File "run.py", line 39, in main
    str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')).replace(' ', '/') + '/'
KeyError: 'name'
---------------error-------------------

and i run this code in this way:
python run.py -f  ./experiments/3dgnn_enet.yaml
